import type {
  PromptBudgetProfile,
  PromptPolicyTier,
  PromptTaskMode,
  ValidatePolicy,
  LLMMode,
} from './types.js';

export const PROMPT_POLICY_TIERS: PromptPolicyTier[] = ['lite', 'balanced'];
export const VALIDATE_POLICIES: ValidatePolicy[] = ['default', 'strict'];
export const LLM_MODES: LLMMode[] = ['standard', 'heavy'];

export const PROMPT_BUDGET_PROFILES: Record<
  PromptPolicyTier,
  Record<PromptTaskMode, PromptBudgetProfile>
> = {
  lite: {
    summarize: {
      header: { baseLines: 8, minLines: 6, maxLines: 12, divisor: 28, lineWindow: 120 },
      skeleton: {
        baseImports: 4,
        minImports: 4,
        maxImports: 8,
        importDivisor: 4,
        baseExports: 8,
        minExports: 6,
        maxExports: 12,
        exportDivisor: 3,
        baseUsages: 6,
        minUsages: 4,
        maxUsages: 10,
        usageDivisor: 4,
        maxImplementationClueLines: 1,
      },
      dependency: { growthDivisor: 14 },
      rule: { growthDivisor: 18, preferredRatio: 0.28 },
      history: { maxResponsibilities: 2 },
      context: { baseTotalChars: 2400, minTotalChars: 1800, maxTotalChars: 3400 },
    },
    validate: {
      header: { baseLines: 7, minLines: 6, maxLines: 10, divisor: 32, lineWindow: 120 },
      skeleton: {
        baseImports: 6,
        minImports: 6,
        maxImports: 10,
        importDivisor: 3,
        baseExports: 10,
        minExports: 8,
        maxExports: 16,
        exportDivisor: 3,
        baseUsages: 8,
        minUsages: 6,
        maxUsages: 14,
        usageDivisor: 3,
        maxImplementationClueLines: 1,
      },
      dependency: { growthDivisor: 16 },
      rule: { growthDivisor: 12, preferredRatio: 0.5 },
      history: { maxResponsibilities: 2 },
      context: { baseTotalChars: 3200, minTotalChars: 2400, maxTotalChars: 4400 },
    },
  },
  balanced: {
    summarize: {
      header: { baseLines: 12, minLines: 12, maxLines: 24, divisor: 20, lineWindow: 160 },
      skeleton: {
        baseImports: 10,
        minImports: 8,
        maxImports: 18,
        importDivisor: 3,
        baseExports: 16,
        minExports: 12,
        maxExports: 28,
        exportDivisor: 2,
        baseUsages: 16,
        minUsages: 12,
        maxUsages: 24,
        usageDivisor: 2,
        maxImplementationClueLines: 3,
      },
      dependency: { growthDivisor: 10 },
      rule: { growthDivisor: 10, preferredRatio: 0.42 },
      history: { maxResponsibilities: 4 },
      context: { baseTotalChars: 5600, minTotalChars: 4200, maxTotalChars: 6800 },
    },
    validate: {
      header: { baseLines: 8, minLines: 8, maxLines: 16, divisor: 30, lineWindow: 120 },
      skeleton: {
        baseImports: 12,
        minImports: 12,
        maxImports: 22,
        importDivisor: 2,
        baseExports: 18,
        minExports: 18,
        maxExports: 30,
        exportDivisor: 2,
        baseUsages: 18,
        minUsages: 18,
        maxUsages: 28,
        usageDivisor: 2,
        maxImplementationClueLines: 2,
      },
      dependency: { growthDivisor: 14 },
      rule: { growthDivisor: 10, preferredRatio: 0.58 },
      history: { maxResponsibilities: 4 },
      context: { baseTotalChars: 6400, minTotalChars: 5200, maxTotalChars: 8000 },
    },
  },
};

export const STRICT_VALIDATE_BUDGET_PROFILES: Record<PromptPolicyTier, PromptBudgetProfile> = {
  lite: {
    header: { baseLines: 7, minLines: 6, maxLines: 12, divisor: 30, lineWindow: 120 },
    skeleton: {
      baseImports: 7,
      minImports: 6,
      maxImports: 12,
      importDivisor: 3,
      baseExports: 11,
      minExports: 8,
      maxExports: 18,
      exportDivisor: 3,
      baseUsages: 9,
      minUsages: 6,
      maxUsages: 16,
      usageDivisor: 3,
      maxImplementationClueLines: 1,
    },
    dependency: { growthDivisor: 16 },
    rule: { growthDivisor: 10, preferredRatio: 0.62 },
    history: { maxResponsibilities: 3 },
    context: { baseTotalChars: 3600, minTotalChars: 2800, maxTotalChars: 5200 },
  },
  balanced: {
    header: { baseLines: 9, minLines: 8, maxLines: 18, divisor: 28, lineWindow: 140 },
    skeleton: {
      baseImports: 14,
      minImports: 12,
      maxImports: 24,
      importDivisor: 2,
      baseExports: 20,
      minExports: 18,
      maxExports: 32,
      exportDivisor: 2,
      baseUsages: 20,
      minUsages: 18,
      maxUsages: 32,
      usageDivisor: 2,
      maxImplementationClueLines: 2,
    },
    dependency: { growthDivisor: 18 },
    rule: { growthDivisor: 8, preferredRatio: 0.72 },
    history: { maxResponsibilities: 6 },
    context: { baseTotalChars: 7800, minTotalChars: 6200, maxTotalChars: 9200 },
  },
};
