version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
      timezone: 'Asia/Shanghai'
    versioning-strategy: 'increase'
    commit-message:
      prefix: 'chore'
      prefix-development: 'chore'
      include: 'scope'
    labels:
      - 'dependencies'
    open-pull-requests-limit: 10

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
      timezone: 'Asia/Shanghai'
    commit-message:
      prefix: 'chore'
      include: 'scope'
    labels:
      - 'dependencies'
