import * as fs from 'fs';
import * as path from 'path';
import type {
  KnowledgeGraph,
  KnowledgeGraphEdge,
  KnowledgeGraphNode,
} from '../../engines/dependency-graph.js';
import type { CycleReport, DeadCodeReport, HubReport } from '../../engines/graph-diagnostics.js';
import { loadRulesFromDir } from '../../infra/rules-loader.js';
import type { SpineConfig } from '../../types/protocol/config.js';
import type { IViewArtifactEnvelope } from '../../types/view.js';
import type { ViewArtifact, ViewContext, ViewProducer } from './producer.js';

// ---------------------------------------------------------------------------
// JSON envelope types
// ---------------------------------------------------------------------------

interface BriefingEntryPoint {
  entrypoint: string;
  summary: string;
}

interface BriefingModule {
  id: string;
  layer: string;
  fanIn: number;
  fanOut: number;
  violationCount: number;
  direction: string;
  inCycle: boolean;
}

interface BriefingConstraint {
  ruleId: string;
  title: string;
  severity: string;
  scope: string[];
  summary: string;
  rationale: string | null;
}

interface BriefingHealthSummary {
  /** Non-compliant dependency edges in the module graph. */
  edgeViolations: number;
  cycleCount: number;
  deadCodeCount: number;
  hubCount: number;
  uniqueCycleParticipants: number;
}

interface AgentBriefingData {
  project: { name: string };
  techStack: Record<string, { extensions: string[]; status: string }> | null;
  entryPoints: Record<string, BriefingEntryPoint[]>;
  moduleTopology: BriefingModule[];
  architectureConstraints: BriefingConstraint[];
  healthSummary: BriefingHealthSummary;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function escapeMarkdownTableCell(value: string): string {
  return value.replace(/\|/g, '\\|').replace(/\n/g, ' ');
}

function escapeMarkdownInline(value: string): string {
  return value.replace(/`/g, '\\`');
}

function classifyDependencyDirection(node: KnowledgeGraphNode): string {
  if (node.fanIn === 0 && node.fanOut === 0) {
    return 'Isolated';
  }
  if (node.fanIn >= node.fanOut * 2) {
    return 'Hub (served)';
  }
  if (node.fanOut >= node.fanIn * 2) {
    return 'Consumer';
  }
  return 'Balanced';
}

function readJsonFile<T>(filePath: string, runtimeIO?: ViewContext['runtimeIO']): T | null {
  try {
    if (!fs.existsSync(filePath)) {
      return null;
    }
    const raw = fs.readFileSync(filePath, 'utf-8');
    return JSON.parse(raw) as T;
  } catch (error) {
    runtimeIO?.warn(
      `[AgentBriefing] Failed to read ${filePath}: ${error instanceof Error ? error.message : String(error)}`,
    );
    return null;
  }
}

// ---------------------------------------------------------------------------
// Section builders
// ---------------------------------------------------------------------------

function buildProjectDefinition(config: SpineConfig | null, rootDir: string): string {
  const name = config?.project?.name || path.basename(rootDir);

  const lines: string[] = [];
  lines.push(`**Project Name:** ${escapeMarkdownInline(name)}`);
  lines.push('');
  lines.push(
    `ArchSpine-managed repository. This briefing is auto-generated by the \`agent-briefing\` view producer and updated on every \`spine sync\`.`,
  );

  return lines.join('\n');
}

function buildTechStack(rootDir: string, runtimeIO?: ViewContext['runtimeIO']): string {
  const languagesPath = path.join(rootDir, '.spine', 'languages.json');
  const languages = readJsonFile<{
    languages: Record<string, { extensions: string[]; status: string }>;
    detectedExtensions: string[];
  }>(languagesPath, runtimeIO);

  if (!languages) {
    return '_Language data not available (`.spine/languages.json` missing)._';
  }

  const lines: string[] = [];
  for (const [lang, info] of Object.entries(languages.languages)) {
    const status = info.status === 'available' ? 'Available' : info.status;
    const exts = info.extensions.map((ext) => `\`${escapeMarkdownInline(ext)}\``).join(', ');
    lines.push(`- **${escapeMarkdownInline(lang)}** (${exts}) — ${status}`);
  }

  if (languages.detectedExtensions && languages.detectedExtensions.length > 0) {
    const uncovered = languages.detectedExtensions.filter(
      (ext) => !Object.values(languages.languages).some((info) => info.extensions.includes(ext)),
    );
    if (uncovered.length > 0) {
      lines.push(
        `- *Unregistered extensions:* ${uncovered.map((e) => `\`${escapeMarkdownInline(e)}\``).join(', ')}`,
      );
    }
  }

  return lines.length > 0 ? lines.join('\n') : '_No languages registered._';
}

function buildEntryPoints(rootDir: string, runtimeIO?: ViewContext['runtimeIO']): string {
  const publicSurfacePath = path.join(rootDir, '.spine', 'view', 'data', 'public-surface.json');
  const raw = readJsonFile<{
    items: Array<{ id: string; entrypoint: string; kind: string; summary: string }>;
  }>(publicSurfacePath, runtimeIO);

  if (!raw || !raw.items || raw.items.length === 0) {
    return '_Public surface data not available (`.spine/view/data/public-surface.json` missing or empty)._';
  }

  const lines: string[] = [];
  const byKind = new Map<string, Array<{ entrypoint: string; summary: string }>>();

  for (const item of raw.items) {
    const list = byKind.get(item.kind) || [];
    list.push({ entrypoint: item.entrypoint, summary: item.summary });
    byKind.set(item.kind, list);
  }

  const kindLabels: Record<string, string> = {
    cli: 'CLI Commands',
    mcp: 'MCP Tools',
    config: 'Configuration',
    schema: 'Schemas',
    route: 'HTTP Routes',
    'public-module': 'Public Modules',
  };

  for (const [kind, entries] of byKind) {
    const label = kindLabels[kind] || kind;
    lines.push(`### ${label}`);
    for (const entry of entries) {
      lines.push(
        `- \`${escapeMarkdownInline(entry.entrypoint)}\` — ${escapeMarkdownInline(entry.summary)}`,
      );
    }
    lines.push('');
  }

  return lines.join('\n');
}

function buildModuleTopology(
  rootDir: string,
  cycleNodes: Set<string>,
  runtimeIO?: ViewContext['runtimeIO'],
): string {
  const kgPath = path.join(rootDir, '.spine', 'view', 'data', 'knowledge-graph.json');
  const kg = readJsonFile<KnowledgeGraph>(kgPath, runtimeIO);

  if (!kg || !kg.nodes || kg.nodes.length === 0) {
    return '_Module topology data not available (`.spine/view/data/knowledge-graph.json` missing or empty). Skipping topology section._';
  }

  // Build set of edge violations for annotation
  const violationEdges = new Map<string, KnowledgeGraphEdge[]>();
  for (const edge of kg.edges) {
    if (!edge.compliant) {
      const list = violationEdges.get(edge.from) || [];
      list.push(edge);
      violationEdges.set(edge.from, list);
    }
  }

  const lines: string[] = [];
  lines.push('| Module | Layer | Fan-In | Fan-Out | Violations | Direction | Cycle |');
  lines.push('| --- | --- | --- | --- | --- | --- | --- |');

  for (const node of kg.nodes) {
    const direction = classifyDependencyDirection(node);
    const inCycle = cycleNodes.has(node.id) ? 'Yes' : '';
    const violationBadges = node.violationCount > 0 ? `**${node.violationCount}**` : '0';
    const cycleBadge = inCycle ? `:warning: ${inCycle}` : '';

    lines.push(
      `| \`${escapeMarkdownTableCell(node.id)}\` | ${escapeMarkdownTableCell(node.layer)} | ${node.fanIn} | ${node.fanOut} | ${violationBadges} | ${direction} | ${cycleBadge} |`,
    );
  }

  // Annotate violation edges
  if (violationEdges.size > 0) {
    lines.push('');
    lines.push('### Violation Edges');
    for (const [from, edges] of violationEdges) {
      for (const edge of edges) {
        const ruleRef = edge.ruleRef ? ` (rule: \`${escapeMarkdownInline(edge.ruleRef)}\`)` : '';
        const msg = edge.message ? `: ${escapeMarkdownInline(edge.message)}` : '';
        lines.push(
          `- \`${escapeMarkdownInline(from)}\` → \`${escapeMarkdownInline(edge.to)}\`${ruleRef}${msg}`,
        );
      }
    }
    lines.push('');
  }

  return lines.join('\n');
}

function buildArchitectureConstraints(
  rootDir: string,
  _runtimeIO?: ViewContext['runtimeIO'],
): string {
  const rulesDir = path.join(rootDir, '.spine', 'rules');
  if (!fs.existsSync(rulesDir)) {
    return '_No rules directory found (`.spine/rules/` missing)._';
  }

  const loadedRules = loadRulesFromDir(rulesDir);
  if (loadedRules.length === 0) {
    return '_No architecture rules defined in `.spine/rules/`._';
  }

  const lines: string[] = [];
  const severityOrder: Record<string, number> = { error: 0, warning: 1, advisory: 2 };
  const sorted = [...loadedRules].sort(
    (a, b) => (severityOrder[a.rule.severity] ?? 1) - (severityOrder[b.rule.severity] ?? 1),
  );

  for (const { rule } of sorted) {
    const severityBadge =
      rule.severity === 'error'
        ? ':no_entry:'
        : rule.severity === 'warning'
          ? ':warning:'
          : ':information_source:';
    const severity = rule.severity.charAt(0).toUpperCase() + rule.severity.slice(1);
    const scope = rule.appliesTo.join(', ');
    lines.push(`- **${escapeMarkdownInline(rule.title)}** (${severityBadge} ${severity})`);
    lines.push(`  - Scope: \`${escapeMarkdownInline(scope)}\``);
    if (rule.summary) {
      lines.push(`  - ${escapeMarkdownInline(rule.summary)}`);
    }
    if (rule.rationale) {
      lines.push(`  - Rationale: ${escapeMarkdownInline(rule.rationale)}`);
    }
  }

  return lines.join('\n');
}

function buildHealthSummary(
  rootDir: string,
  kg: KnowledgeGraph | null,
  cycles: CycleReport[] | null,
  deadCode: DeadCodeReport[] | null,
  hubs: HubReport[] | null,
): string {
  // Non-compliant dependency edges in the module graph
  const edgeViolations = kg ? kg.edges.filter((e) => !e.compliant).length : 0;

  const cycleCount = cycles ? cycles.length : 0;
  const deadCodeCount = deadCode ? deadCode.length : 0;
  const hubCount = hubs ? hubs.length : 0;

  // Compute cycle participant set
  const cycleParticipants = new Set<string>();
  if (cycles) {
    for (const cycle of cycles) {
      for (const nodeId of cycle.nodes) {
        cycleParticipants.add(nodeId);
      }
    }
  }

  const lines: string[] = [];
  lines.push('| Metric | Value |');
  lines.push('| --- | --- |');
  lines.push(
    `| Dependency edge violations | ${edgeViolations > 0 ? `**${edgeViolations}**` : '0'} |`,
  );
  lines.push(`| Cyclic dependencies detected | ${cycleCount > 0 ? `**${cycleCount}**` : '0'} |`);
  lines.push(`| Dead code candidates | ${deadCodeCount > 0 ? `**${deadCodeCount}**` : '0'} |`);
  lines.push(
    `| Hub modules (>= 95th percentile fan-in) | ${hubCount > 0 ? `**${hubCount}**` : '0'} |`,
  );

  if (cycles && cycles.length > 0) {
    lines.push('');
    lines.push('### Cyclic Dependencies');

    // Deduplicate cycle participants
    const uniqueParticipants = Array.from(cycleParticipants).sort();
    lines.push(
      `**${uniqueParticipants.length}** modules participate in **${cycles.length}** cycles.`,
    );
    lines.push('');

    // List top 5 largest cycles
    const topCycles = [...cycles].sort((a, b) => b.length - a.length).slice(0, 5);
    for (const cycle of topCycles) {
      lines.push(`- \`${escapeMarkdownInline(cycle.cycleId)}\` (${cycle.length} nodes)`);
    }
  }

  if (deadCode && deadCode.length > 0) {
    lines.push('');
    lines.push('### Dead Code Candidates');
    for (const dc of deadCode) {
      lines.push(
        `- \`${escapeMarkdownInline(dc.moduleId)}\` (${dc.confidence}) — ${escapeMarkdownInline(dc.reason)}`,
      );
    }
  }

  if (hubs && hubs.length > 0) {
    lines.push('');
    lines.push('### Hub Modules (Top Fan-In)');
    for (const hub of hubs.slice(0, 5)) {
      lines.push(
        `- \`${escapeMarkdownInline(hub.moduleId)}\` — fan-in: ${hub.fanIn}, percentile: ${hub.percentile}`,
      );
    }
  }

  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Derivation
// ---------------------------------------------------------------------------

async function deriveAgentBriefing(ctx: ViewContext): Promise<ViewArtifact> {
  const { rootDir } = ctx;

  // Load config
  const configPath = path.join(rootDir, '.spine', 'config.json');
  const config = readJsonFile<SpineConfig>(configPath, ctx.runtimeIO);

  // Load knowledge graph
  const kgPath = path.join(rootDir, '.spine', 'view', 'data', 'knowledge-graph.json');
  const kg = readJsonFile<KnowledgeGraph>(kgPath, ctx.runtimeIO);

  // Load diagnostics
  const cyclesPath = path.join(rootDir, '.spine', 'view', 'data', 'diagnostics', 'cycles.json');
  const deadCodePath = path.join(
    rootDir,
    '.spine',
    'view',
    'data',
    'diagnostics',
    'dead-code.json',
  );
  const hubsPath = path.join(rootDir, '.spine', 'view', 'data', 'diagnostics', 'hubs.json');

  const cycles = readJsonFile<CycleReport[]>(cyclesPath, ctx.runtimeIO);
  const deadCode = readJsonFile<DeadCodeReport[]>(deadCodePath, ctx.runtimeIO);
  const hubs = readJsonFile<HubReport[]>(hubsPath, ctx.runtimeIO);

  // Compute cycle participant set for topology annotations
  const cycleNodes = new Set<string>();
  if (cycles) {
    for (const cycle of cycles) {
      for (const nodeId of cycle.nodes) {
        cycleNodes.add(nodeId);
      }
    }
  }

  // Build each section
  const projectName = config?.project?.name || path.basename(rootDir);

  const sections: string[] = [];

  sections.push(`# ${escapeMarkdownInline(projectName)} — Agent Briefing`);
  sections.push('');

  sections.push('## Project Definition');
  sections.push('');
  sections.push(buildProjectDefinition(config, rootDir));
  sections.push('');

  sections.push('## Tech Stack');
  sections.push('');
  sections.push(buildTechStack(rootDir, ctx.runtimeIO));
  sections.push('');

  sections.push('## Entry Point Map');
  sections.push('');
  sections.push(buildEntryPoints(rootDir, ctx.runtimeIO));
  sections.push('');

  sections.push('## Module Topology');
  sections.push('');
  sections.push(buildModuleTopology(rootDir, cycleNodes, ctx.runtimeIO));
  sections.push('');

  sections.push('## Architecture Constraints');
  sections.push('');
  sections.push(buildArchitectureConstraints(rootDir, ctx.runtimeIO));
  sections.push('');

  sections.push('## Health Summary');
  sections.push('');
  sections.push(buildHealthSummary(rootDir, kg, cycles, deadCode, hubs));
  sections.push('');

  sections.push('');
  sections.push('---');
  sections.push(
    `*Generated at ${new Date().toISOString()} by ArchSpine agent-briefing view producer.*`,
  );

  const markdown = sections.join('\n');

  // ---------------------------------------------------------------------------
  // Build structured JSON
  // ---------------------------------------------------------------------------

  const entryPointsJson: Record<string, BriefingEntryPoint[]> = {};
  const publicSurfacePath = path.join(rootDir, '.spine', 'view', 'data', 'public-surface.json');
  const psRaw = readJsonFile<{
    items: Array<{ entrypoint: string; kind: string; summary: string }>;
  }>(publicSurfacePath, ctx.runtimeIO);
  if (psRaw?.items) {
    for (const item of psRaw.items) {
      const list = entryPointsJson[item.kind] || [];
      list.push({ entrypoint: item.entrypoint, summary: item.summary });
      entryPointsJson[item.kind] = list;
    }
  }

  const topologyJson: BriefingModule[] = (kg?.nodes || []).map((node) => ({
    id: node.id,
    layer: node.layer,
    fanIn: node.fanIn,
    fanOut: node.fanOut,
    violationCount: node.violationCount,
    direction: classifyDependencyDirection(node),
    inCycle: cycleNodes.has(node.id),
  }));

  const rulesDir = path.join(rootDir, '.spine', 'rules');
  const constraintsJson: BriefingConstraint[] = [];
  if (fs.existsSync(rulesDir)) {
    const loadedRules = loadRulesFromDir(rulesDir);
    for (const { rule } of loadedRules) {
      constraintsJson.push({
        ruleId: rule.ruleId,
        title: rule.title,
        severity: rule.severity,
        scope: rule.appliesTo,
        summary: rule.summary,
        rationale: rule.rationale ?? null,
      });
    }
  }

  const techStackJson = readJsonFile<{
    languages: Record<string, { extensions: string[]; status: string }>;
  }>(path.join(rootDir, '.spine', 'languages.json'));

  const envelope: IViewArtifactEnvelope<AgentBriefingData> = {
    schemaVersion: '2.0.0',
    generatedAt: new Date().toISOString(),
    viewType: 'agent-briefing',
    summary: `ArchSpine agent briefing for ${escapeMarkdownInline(projectName)}. ${kg?.nodes?.length ?? 0} modules, ${kg?.edges?.length ?? 0} edges, ${constraintsJson.length} rules.`,
    items: [
      {
        project: {
          name: projectName,
        },
        techStack: techStackJson?.languages ?? null,
        entryPoints: entryPointsJson,
        moduleTopology: topologyJson,
        architectureConstraints: constraintsJson,
        healthSummary: {
          edgeViolations: kg ? kg.edges.filter((e) => !e.compliant).length : 0,
          cycleCount: cycles?.length || 0,
          deadCodeCount: deadCode?.length || 0,
          hubCount: hubs?.length || 0,
          uniqueCycleParticipants: cycleNodes.size,
        },
      },
    ],
    _quality: {
      nodeCount: kg?.nodes?.length ?? 0,
      edgeCount: kg?.edges?.length ?? 0,
      cycleCount: cycles?.length ?? 0,
      deadCodeCount: deadCode?.length ?? 0,
      hubCount: hubs?.length ?? 0,
      totalCandidatesEvaluated: constraintsJson.length,
      selectionRate: `${topologyJson.length} modules, ${constraintsJson.length} rules`,
    },
  };

  ctx.outputManager.saveView('agent-briefing.json', envelope);
  ctx.outputManager.saveViewMarkdown('agent-briefing.md', markdown);

  ctx.runtimeIO?.info(`[View] Wrote agent briefing for project "${projectName}".`);

  const hasKg = kg !== null;
  const hasDiagnostics = cycles !== null && deadCode !== null && hubs !== null;

  return {
    viewType: 'agent-briefing',
    generated: true,
    generatedAt: new Date().toISOString(),
    metrics: {
      moduleCount: kg?.nodes?.length || 0,
      edgeCount: kg?.edges?.length || 0,
      violationCount: kg ? kg.edges.filter((e) => !e.compliant).length : 0,
      cycleCount: cycles?.length || 0,
      deadCodeCount: deadCode?.length || 0,
      hubCount: hubs?.length || 0,
      hasKnowledgeGraph: hasKg ? 1 : 0,
      hasDiagnostics: hasDiagnostics ? 1 : 0,
    },
  };
}

export const agentBriefingProducer: ViewProducer = {
  async derive(ctx: ViewContext): Promise<ViewArtifact> {
    return deriveAgentBriefing(ctx);
  },
};
