blank_issues_enabled: false
contact_links:
  - name: 'Questions & Discussions'
    url: 'https://github.com/archspine-ai/archspine/discussions'
    about: 'Please use GitHub Discussions for Q&A and general talk.'
