import { SpineTask, TaskContext } from '../core/task.js';
import type { CommitStageOutput } from '../core/task-types.js';
import { TaskRunner } from '../core/pipeline.js';
import { AggregationTask } from './aggregate.js';
import { ReverseIndexingTask } from './reverse-index.js';
import { KnowledgeGraphTask } from './knowledge-graph.js';
import { ViewDerivationTask } from './view-derivation.js';
import { ViewService } from '../services/view/view-service.js';
import { VIEW_DEFINITIONS } from '../services/view/view-registry.js';

const SPINE_README = [
  '# ArchSpine Control Plane',
  '',
  'This directory (`.spine/`) is an ArchSpine control plane — a machine-readable semantic layer that helps AI agents understand this codebase.',
  '',
  '## For AI Agents',
  '',
  'Start here:',
  '1. Read `view/pages/agent-briefing.md` for project overview, module topology, and architecture constraints',
  '2. Query `view/knowledge-graph.json` for module dependency graph',
  '3. Check `view/data/diagnostics/` for health reports (cycles, dead code, hub modules)',
  '',
  '## MCP Tools',
  '',
  'If the ArchSpine MCP server is connected, use these tools:',
  '- `spine_query_graph` — query module dependencies',
  '- `spine_get_diagnostics` — get health reports',
  '- `spine_match_semantic` — find modules by role/responsibility',
  '- `spine_get_change_impact` — assess change impact',
  '- `spine_get_module_context` — get full module context',
  '',
  'Generated by ArchSpine. Do not edit manually.',
  '',
].join('\n');

export class PostCommitDerivationTask extends SpineTask<CommitStageOutput, void> {
  name = 'Post-Commit Derivation';
  checkpointId = 'post-commit-derivation';

  constructor(private readonly viewLayer: boolean) {
    super();
  }

  async execute(ctx: TaskContext, input: CommitStageOutput): Promise<void> {
    const runner = new TaskRunner(ctx);
    await runner.run(new ReverseIndexingTask(), input);

    if (ctx.hookMode) {
      return;
    }

    await runner.run(new AggregationTask(), input);

    this.writeSpineReadme(ctx);

    await runner.run(new KnowledgeGraphTask(), input);

    if (this.viewLayer) {
      await runner.run(new ViewDerivationTask(), input);
      return;
    }

    const viewService = new ViewService(
      ctx.rootDir,
      ctx.outputManager,
      ctx.runtimeIO,
      ctx.llmClient,
    );
    viewService.clearViewArtifacts(VIEW_DEFINITIONS.map((definition) => definition.id));
  }

  /**
   * Writes .spine/SPINE.md — a self-describing entry point that helps AI agents
   * discover the control plane with zero external dependencies.
   */
  private writeSpineReadme(ctx: TaskContext): void {
    ctx.outputManager.saveGodDoc('SPINE.md', SPINE_README);
  }
}
